export enum ValidateProfileError {
  INCORRECT_USER_DATA = "INCORRECT USER DATA",
  INCORRECT_AGE = "INCORRECT AGE",
  INCORRECT_CITY = "INCORRECT CITY",
  SERVER_ERROR = "SERVER ERROR",
  NO_DATA = "NO DATA",
}
